---
title       : NMIS Energy Data Overview
subtitle    : 
author      : Data Team, Modi Research Group
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}

---

```{r echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE}
setwd("~/Code/presentations/prabhas/energy-summaries/")
source("../NigeriaPresentationUtils.R")
# importing variables... this is how we have to do it sadly
lgas <- lgas
lgashp <- lgashp
lga_map <- lga_map
flipAndPrint <- flipAndPrint
states <- states
stateCenters <- stateCenters
```
## Outline
1. Localities Survey, coverage
2. Other surveys, what data is included
3. LGA wides summaries of data
4. Katsina -- 4 LGA example of detailed demand analysis

---

## Coverage of localities survey (1)
```{r echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE}
source("~/Code/formhub.R/R/formhub.R")
library(doBy)
loc <- formhubRead("data/Local_661_Merged.csv", "data/Localities_05_06_2012.json")
locsp <- as.SpatialPointsDataFrame(loc)
locppp <- as(locsp, "ppp")

loc <- rename(loc, c("X_lga_id" = "lga_id"))
lgas <- read.csv("~/Dropbox/Nigeria/Nigeria 661 Baseline Data Cleaning/lgas.csv")
loc <- merge(loc, lgas, by="lga_id")


loc$hhnum <- as.numeric(recodeVar(as.character(loc$households_number), 
                       src=c("101_to_250_hh", "21_to_50_hh", "251_to_500_hh", "51_to_100_hh","less_20_hh","more_500_hh"),
                       tgt=c('175', '35', '375', '75', '10', '750'), default=NA, keep.na=T))
library(ggplot2)
ggplot(data=loc, aes(x=X_gps_longitude, y=X_gps_latitude)) + geom_point() + stat_density2d(aes(fill = ..level..), geom="polygon")
```

---

## Coverage of localities survey (2)
Household aggregate -- taking the mid-points of the bin vs. population of LGA
```{r echo=F, warning=F, message=F, comment=NA, fig.height=8, fig.width=6, cache=TRUE}
lgaloc <- ddply(idata.frame(loc), .(lga_id), function(df) {
  data.frame(
    lga_id = df[1,'lga_id'],
    zone = df[1, 'zone'],
    HouseholdAggregate = sum(df$hhnum, na.rm=T),
    Population = df[1,'pop_2006'],
    Density = df[1,'pop_density_2006']
    )
})
ggplot(lgaloc, aes(y=Population, x=HouseholdAggregate)) + geom_point() + geom_abline(slope=6)
```
Line: 6 households / person. No correlation, even when separated by zone.

---

## 